In [1]:
import numpy as np   #np as alias we took of numpy,

In [2]:
myarr = np.array([2,4,77,6] )   #array() as np method 1-Dimensional array

In [3]:
myarr

array([ 2,  4, 77,  6])

In [4]:
type(myarr)

numpy.ndarray

In [5]:
myarr.shape #1-D array

(4,)

In [6]:
#array of 2D also called Matrix in maths

In [7]:
my2D = np.array([[2,3,4999,7],[4,5,1,2]]) #in this we have two rows starting with 0th row by default

In [8]:
my2D[0,3] #for retreiving data

7

In [9]:
my2D.shape  #it has 2 rows and 4 columns in 2-D array

(2, 4)

In [10]:
my2D.dtype  #to know of which type it is

dtype('int32')

In [11]:
my2D[0,0] #retrieving the value of 0th row and 0th column

2

In [12]:
my2D[0,0]=98  #changing the value of 0th row and 0th column of 2-D

In [13]:
my2D

array([[  98,    3, 4999,    7],
       [   4,    5,    1,    2]])

#ARRAY CREATION

In [15]:
np.array([[1,2,3],[3,5,4]]) #creation from python object i.e. python list into 2D array

array([[1, 2, 3],
       [3, 5, 4]])

In [16]:
np.array([[1,2,3],[3,5,4]]).dtype

dtype('int32')

In [17]:
np.array({3,4,5,6})   #dtype =object is not efficient if we do any math calcs {prefernce to dtype in (int8,32,64 or float64) for effiecent calcs}

array({3, 4, 5, 6}, dtype=object)

In [18]:
arr_1 = np.zeros((2,5))   #creation of numpy array with zeros &  rows=2 and columns=5

In [19]:
arr_1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
arr_1.dtype

dtype('float64')

In [21]:
arr_1.shape

(2, 5)

In [22]:
arr = np.arange(10)    #creation of numpy array from arange() method  

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
space = np.linspace(1,4,5)  #here 5 is total elements needed in 1-D array

In [25]:
space

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [26]:
type(space)

numpy.ndarray

In [27]:
ide= np.identity(45)   #creation of numpy array from identity() method of np having 45x45

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [66]:
ide.shape #matrix of 45x45

(45, 45)

In [68]:
ide.size

2025

In [70]:
ide.dtype

dtype('float64')

In [72]:
arr1 = np.arange(50)

In [74]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [76]:
arr1 = arr1.reshape(5,10)  #it will convert into 5x10 i.e. 5 rows and 10 columns

In [78]:
arr1  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arr1.shape

(5, 10)

In [82]:
#now again i want to convert into original array shape ,so use ravel() method

In [84]:
arr1=arr1.ravel()

In [86]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [90]:
arr1.shape #again it got converted into the 1D array original 

(50,)

In [ ]:
                     #About axis in array

In [92]:
x= [[1,2,3],[4,5,6],[7,1,0]]   #2-D

In [94]:
ar = np.array(x)

In [96]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [110]:
#Remember :
#in 1D array we have axis=0 only
#in 2D array we have two axis i.e. axis=0 (towards row downward ) and axis=1 (towards column sideward) 

In [104]:
ar.sum(axis=0)  #this shows axis=0 sum of rows   

array([12,  8,  9])

In [112]:
ar.sum(axis=1) #this shows axis=1 sum of cols.

array([ 6, 15,  8])

In [116]:
#to find transpose of an array

In [118]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [120]:
ar.ndim #dimension

2

In [122]:
ar.shape

(3, 3)

In [124]:
ar.size

9

In [126]:
ar.nbytes  #it tells how much my array's elements are consuming space


36

In [130]:
#MEthods of 1D array

In [132]:
one= np.array([2,55,4,3])

In [134]:
one

array([ 2, 55,  4,  3])

In [138]:
one.argmax() #this method return the index where max value is present

1

In [140]:
one.argmin()

0

In [142]:
one.argsort() #return indices in array format where values are present in ASC order

array([0, 3, 2, 1], dtype=int64)

In [146]:
ar   #2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [144]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [148]:
ar.argmin()

8

In [150]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [152]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [154]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [156]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [164]:
ar.reshape(9,)  #into 1D

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [170]:
ar.reshape(9,1)  #into 2D

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [172]:
#mathematical/matrix  operations in numpy 

In [175]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [177]:
ar2= np.array([[2,3,4],[4,5,1],[8,7,6]])

In [179]:
ar2

array([[2, 3, 4],
       [4, 5, 1],
       [8, 7, 6]])

In [181]:
ar + ar2  #Addition

array([[ 3,  5,  7],
       [ 8, 10,  7],
       [15,  8,  6]])

In [183]:
ar - ar2  #subtraction

array([[-1, -1, -1],
       [ 0,  0,  5],
       [-1, -6, -6]])

In [185]:
ar * ar2  #element wise multp.

array([[ 2,  6, 12],
       [16, 25,  6],
       [56,  7,  0]])

In [187]:
np.sqrt(ar)  #square root of ar array elements

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [191]:
ar.sum()

29

In [193]:
ar.max()  #return max element

7

In [195]:
ar.argmax() #return index

6

In [197]:
ar.min()

0

In [199]:
 np.where(ar>5) #it will return index where the elements greater then 5 available in whole array/matrix

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [201]:
np.count_nonzero(ar) #total elements which have non zero values are 8

8

In [203]:
np.nonzero(ar)     

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))